# Site settings
title: Nordic Beta Labs
description: 'Stockholm, building online software that people need'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Colin Treseler'
  email: team@appaction.io
  twitter_username: nordicbetalabs
  facebook_username: nordicbetalabs
  github_username:  nordicbetalabs
  linkedin_username:  nordicbetalabs

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
